// Record every read-aloud sentence with a natural voice: node scripts/make-voice.js
// Finds the sentences (scripts/voice-lines.js), records the new ones with Kokoro through
// scripts/voice-tts.py, encodes them to AAC in audio/voice/, removes clips no longer used,
// and writes the lookup table js/voice-clips.js. Needs macOS (afconvert) and uv (brew install uv).
const fs = require('fs');
const os = require('os');
const path = require('path');
const crypto = require('crypto');
const { execFileSync } = require('child_process');
const { voiceLines } = require('./voice-lines.js');

const VOICE = 'af_heart';
const SPEED = 0.95;
const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'audio/voice');
const TABLE = path.join(ROOT, 'js/voice-clips.js');
// Words Kokoro says wrongly, spelled out in its phonemes (A = ay, O = oh; ˈ main stress, ˌ light stress).
const PRONOUNCE = { 'Éléonore': '/ɛlˌiOnˈɔɹ/' };
const spoken = (text) => Object.entries(PRONOUNCE).reduce((t, [word, ph]) => t.split(word).join(`[${word}](${ph})`), text);

const lines = voiceLines();
const idFor = (text) => crypto.createHash('sha1').update(`${VOICE}|${SPEED}|${spoken(text)}`).digest('hex').slice(0, 12);
const clips = new Map([...lines].map(([key, text]) => [key, idFor(text)]));
fs.mkdirSync(OUT, { recursive: true });

const todo = [...lines].filter(([key]) => !fs.existsSync(path.join(OUT, `${clips.get(key)}.m4a`)))
  .map(([key, text]) => ({ id: clips.get(key), text: spoken(text) }));
console.log(`${lines.size} sentences, ${todo.length} to record`);

if (todo.length) {
  // A short path: the espeak library Kokoro uses cuts paths at 160 characters.
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'cqv-'));
  fs.writeFileSync(path.join(tmp, 'lines.json'), JSON.stringify(todo));
  execFileSync('uv', ['run', '--quiet', '--python', '3.12', '--with', 'kokoro>=0.9.4', '--with', 'transformers>=4.45', '--with', 'soundfile',
    'python', path.join(__dirname, 'voice-tts.py'), path.join(tmp, 'lines.json'), tmp, VOICE, String(SPEED)], { stdio: 'inherit' });
  for (const { id } of todo) {
    execFileSync('afconvert', ['-f', 'm4af', '-d', 'aac', '-b', '40000', path.join(tmp, `${id}.wav`), path.join(OUT, `${id}.m4a`)]);
  }
  fs.rmSync(tmp, { recursive: true, force: true });
}

const used = new Set(clips.values());
for (const f of fs.readdirSync(OUT)) if (!used.has(path.basename(f, '.m4a'))) fs.unlinkSync(path.join(OUT, f));

const entries = [...clips].sort(([a], [b]) => a.localeCompare(b)).map(([key, id]) => `    ${JSON.stringify(key)}: '${id}',`);
fs.writeFileSync(TABLE, `/* Generated by scripts/make-voice.js: do not edit. Sentence key -> clip in audio/voice/. */
(function (root) {
  const api = { voice: '${VOICE}', clips: {
${entries.join('\n')}
  } };
  root.VoiceClips = api;
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
})(typeof window !== 'undefined' ? window : globalThis);
`);
const kb = [...used].reduce((n, id) => n + fs.statSync(path.join(OUT, `${id}.m4a`)).size, 0) / 1024;
console.log(`js/voice-clips.js: ${used.size} clips, ${kb.toFixed(0)} KB`);
