// Pick easy, popular puzzles from the Lichess puzzle database (CC0) and write js/lichess-puzzles.js.
//   curl -sL https://database.lichess.org/lichess_db_puzzle.csv.zst | zstd -dc > puzzles.csv
//   node scripts/make-lichess.js puzzles.csv
// Every puzzle is replayed with our own engine, and turned round when needed so the player is White.
const fs = require('fs');
const path = require('path');
const readline = require('readline');
const C = require('../js/engine.js');

const OUT = path.resolve(__dirname, '../js/lichess-puzzles.js');
const PER_LEVEL = 60;
// Lichess puzzle rating bands for levels 1 to 4.
const BANDS = [[0, 800], [800, 1000], [1000, 1200], [1200, 1450]];

// Our puzzle types, in the order they are tried, so each puzzle lands in one type only.
const TYPES = [
  { id: 'backRank', tag: 'backRankMate', mate: true },
  { id: 'promote', tag: 'promotion', needPromo: true },
  { id: 'pin', tag: 'pin' },
  { id: 'skewer', tag: 'skewer' },
  { id: 'discover', tag: 'discoveredAttack' },
  { id: 'double', tag: 'fork' },
];

const flipSq = (s) => s[0] + (9 - +s[1]);
const flipUci = (u) => flipSq(u.slice(0, 2)) + flipSq(u.slice(2, 4)) + u.slice(4);
const swapCase = (ch) => (ch === ch.toUpperCase() ? ch.toLowerCase() : ch.toUpperCase());
// Swap the colours and mirror the ranks: the same puzzle with the player as White.
function flipFEN(fen) {
  const [board, turn, castling, ep, half, full] = fen.split(' ');
  const rows = board.split('/').reverse().map((r) => [...r].map(swapCase).join(''));
  const cast = castling === '-' ? '-' : 'KQkq'.split('').filter((c) => [...castling].map(swapCase).includes(c)).join('');
  return [rows.join('/'), turn === 'w' ? 'b' : 'w', cast, ep === '-' ? '-' : flipSq(ep), half, full].join(' ');
}

const isMate = (pos) => C.inCheck(pos) && C.legalMoves(pos).length === 0;

// [setupFen, setupMove, line] with White to play the line, or null if anything does not check out.
function prepare(fen, moves, type) {
  if (fen.split(' ')[1] === 'w') { fen = flipFEN(fen); moves = moves.map(flipUci); }
  let pos = C.parseFEN(fen);
  for (let i = 0; i < moves.length; i++) {
    const m = C.fromUCI(pos, moves[i]);
    if (!m) return null;
    if (i % 2 === 1 && m.promo && m.promo !== 'Q') return null; // keep to queen promotions
    pos = C.makeMove(pos, m);
  }
  if (type.mate && !isMate(pos)) return null;
  if (type.needPromo && !moves.some((u, i) => i % 2 === 1 && u.length === 5)) return null;
  return [fen, moves[0], moves.slice(1).join(' ')];
}

async function main() {
  const file = process.argv[2];
  if (!file) { console.error('Usage: node scripts/make-lichess.js <lichess_db_puzzle.csv>'); process.exit(1); }
  const pools = Object.fromEntries(TYPES.map((t) => [t.id, BANDS.map(() => [])]));
  const rl = readline.createInterface({ input: fs.createReadStream(file), crlfDelay: Infinity });
  for await (const line of rl) {
    const f = line.split(',');
    const [id, fen, mv, rating, dev, pop, plays, tags] = f;
    if (id === 'PuzzleId') continue;
    const r = +rating, moves = mv.split(' ');
    // A move by the other side, then one or two moves to find.
    if (moves.length !== 2 && moves.length !== 4) continue;
    if (+dev > 80 || +pop < 85 || +plays < 1000 || r > BANDS[3][1]) continue;
    const t = ` ${tags} `;
    if (t.includes(' long ') || t.includes(' veryLong ')) continue;
    const type = TYPES.find((ty) => t.includes(` ${ty.tag} `));
    if (!type) continue;
    const band = BANDS.findIndex(([lo, hi]) => r > lo && r <= hi);
    pools[type.id][band].push({ id, fen, moves, r, score: +pop * Math.log(+plays) });
  }
  const out = {};
  for (const type of TYPES) {
    out[type.id] = pools[type.id].map((pool) => {
      pool.sort((a, b) => b.score - a.score);
      const picked = [];
      for (const p of pool) {
        if (picked.length >= PER_LEVEL) break;
        const prep = prepare(p.fen, p.moves, type);
        if (prep) picked.push([p.id, ...prep, p.r]);
      }
      return picked.sort((a, b) => a[4] - b[4]);
    });
    console.log(type.id, out[type.id].map((l) => l.length).join(' / '));
  }
  const body = TYPES.map((t) => `    ${t.id}: [\n${out[t.id].map((lvl) => `      [\n${lvl.map((p) => `        ${JSON.stringify(p)},`).join('\n')}\n      ],`).join('\n')}\n    ],`).join('\n');
  fs.writeFileSync(OUT, `/* Generated by scripts/make-lichess.js from the Lichess puzzle database (CC0): do not edit.
 * type -> 4 levels -> [lichessId, fen before Black's move, Black's move, White's line, rating]. */
(function (root) {
  const api = {
${body}
  };
  root.LichessPuzzles = api;
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
})(typeof window !== 'undefined' ? window : globalThis);
`);
  console.log(`${path.relative(process.cwd(), OUT)}: ${(fs.statSync(OUT).size / 1024).toFixed(0)} KB`);
}

main();
